services:
  # --- Service 1: Le nœud Publicateur ---
  publisher:
    container_name: ros_publisher_99
    # Utilise directement l'image de base légère
    image: ros:humble-ros-core
    network_mode: "host"

    environment:
      # L'ID de domaine ROS 2, comme demandé
      - ROS_DOMAIN_ID=99
    
    # Monte le répertoire 'app' de l'hôte
    # dans le répertoire '/app' du conteneur.
    # 'ro' (read-only) est une bonne pratique car le conteneur n'a pas besoin d'écrire sur les scripts.
    volumes:
      - ./app:/app:ro

    # Définit le répertoire de travail à l'intérieur du conteneur
    working_dir: /app
    
    command: >
      bash -c "source /opt/ros/humble/setup.bash && 
               python3 ./publisher_node.py"

  # --- Service 2: Le nœud Calculateur ---
  calculator:
    container_name: ros_calculator_99
    # Utilise la même image de base
    image: ros:humble-ros-core

    network_mode: "host"

    environment:
      # Doit être sur le MÊME ID de domaine pour communiquer
      - ROS_DOMAIN_ID=99
    
    # Monte également le répertoire des scripts
    volumes:
      - ./app:/app:ro

    # Définit le répertoire de travail
    working_dir: /app
      
    command: >
      bash -c "source /opt/ros/humble/setup.bash && 
               python3 ./calculator_node.py"
    
    depends_on:
      - publisher